### PR TITLE
Create dasar pemrograman

### PR DESCRIPTION
**Pull request by nasrullah2000**
Saya = input('Masukkan berat badan rekan anda {kg}')
Rekan = input('Masukkan berat badan rekan anda {kg}')
Rekan = int(Rekan)
Saya = int(Saya)
Hasil1 = Rekan - Saya
Hasil2 = Saya - Rekan

if Rekan > Saya:
       kategori = 'Anda lebih ringan', int(Hasil1),'kg dari pada rekan anda'
			 
elif Saya > Rekan:
       kategori = 'Anda lebih berat', int(Hasil2),'kg dari rekan anda'
			 
else:
       kategori = 'Berat badan anda sama dengan rekan anda'
			 
print('{}'.format (kategori))

### CODE REVIEW

**Comment by arifrh007** [comment]
Wkwk kenapa kamu copas dikoment

**Comment by ewinsutriandi** [comment]
> Wkwk kenapa kamu copas dikoment

Arif ajarin teman-temannya ya

**Comment by ewinsutriandi** [comment]
masih salah

**Comment by arifrh007** [comment]
Siap pak!

Dikirim dari ponsel cerdas Samsung Galaxy saya.
-------- Pesan asli --------Dari: Aswian Editri Sutriandi <notifications@github.com> Tanggal: 06/11/18  07:06  (GMT+08:00) Ke: "ewinsutriandi/ewinsutriandi.github.io" <ewinsutriandi.github.io@noreply.github.com> Cc: ARIF RAHMAN HAKIM <cintok28@gmail.com>, Comment <comment@noreply.github.com> Subjek: Re: [ewinsutriandi/ewinsutriandi.github.io] Create dasar pemrograman (#9) 

Wkwk kenapa kamu copas dikoment

Arif ajarin teman-temannya ya

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ewinsutriandi/ewinsutriandi.github.io","title":"ewinsutriandi/ewinsutriandi.github.io","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ewinsutriandi/ewinsutriandi.github.io"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ewinsutriandi in #9: \u003e Wkwk kenapa kamu copas dikoment\r\n\r\nArif ajarin teman-temannya ya"}],"action":{"name":"View Pull Request","url":"https://github.com/ewinsutriandi/ewinsutriandi.github.io/pull/9#issuecomment-436069707"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ewinsutriandi/ewinsutriandi.github.io/pull/9#issuecomment-436069707",
"url": "https://github.com/ewinsutriandi/ewinsutriandi.github.io/pull/9#issuecomment-436069707",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [ewinsutriandi/ewinsutriandi.github.io] Create dasar pemrograman (#9)",
"sections": [
{
"text": "",
"activityTitle": "**Aswian Editri Sutriandi**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ewinsutriandi",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ewinsutriandi/ewinsutriandi.github.io\",\n\"issueId\": 9,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close pull request",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"PullRequestClose\",\n\"repositoryFullName\": \"ewinsutriandi/ewinsutriandi.github.io\",\n\"pullRequestId\": 9\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/ewinsutriandi/ewinsutriandi.github.io/pull/9#issuecomment-436069707"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 406420620\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by arifrh007** [comment]
Siap pak!

**Pull request closed without merging**
